version: "3.9"
services:
 restaurant-service:
  image: r0930134/basisproject
  ports:
    - "8000:8000"

 mysql:
  image: mysql:latest
  volumes:
    - restaurant-data:/code/mysqldb
  environment:
    MYSQL_ROOT_PASSWORD: your_password
    MYSQL_DATABASE: your_database

volumes:
  restaurant_data: