version: "3.9"
services:
 restaurant-service:
  image: r0930134/basisproject
  ports:
    - "8000:8000"

 mysql:
   image: mysql:latest
    volumes:
      - restaurant-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123!
      MYSQL_DATABASE: restaurantdb

volumes:
  restaurant_data: